/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
/*
synchronized public void win_draw1(GWinApplet appc, GWinData data) { //_CODE_:GUI:651654:
  appc.background(230);
} //_CODE_:GUI:651654:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:objList:305444:
  println("objList - GDropList event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:objList:305444:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:894643:
  println("button1 - GButton event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:button1:894643:

public void dropList1_click2(GDropList source, GEvent event) { //_CODE_:schemeList1:924018:
  println("schemeList1 - GDropList event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:schemeList1:924018:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  GUI = new GWindow(this, "GUI Window", 0, 0, 240, 335, false, JAVA2D);
  GUI.addDrawHandler(this, "win_draw1");
  objList = new GDropList(GUI.papplet, 7, 25, 101, 105, 5);
  objList.setItems(loadStrings("list_305444"), 0);
  objList.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  objList.addEventHandler(this, "dropList1_click1");
  button1 = new GButton(GUI.papplet, 132, 20, 80, 30);
  button1.setText("Load Obj");
  button1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  schemeList1 = new GDropList(GUI.papplet, 8, 118, 100, 48, 2);
  schemeList1.setItems(loadStrings("list_924018"), 0);
  schemeList1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  schemeList1.addEventHandler(this, "dropList1_click2");
  label1 = new GLabel(GUI.papplet, 11, 169, 213, 150);
  label1.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label1.setText("My label");
  label1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label1.setOpaque(false);
  label2 = new GLabel(GUI.papplet, 130, 117, 92, 30);
  label2.setText("Select Method");
  label2.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GWindow GUI;
GDropList objList; 
GButton button1; 
GDropList schemeList1; 
GLabel label1; 
GLabel label2; 
*/
